# Zepp-Life-Plugin 默认配置文件

autoStep:
  # 是否开启自动刷步数（全局开关，对所有开启了自动刷步的绑定用户生效）
  enabled: true
  
  # 自动刷步的 Cron 时间表达式（默认每天晚上 20:30 执行）
  cron: "0 30 20 * * ?"
  
  # 自动刷步或未指定步数时的随机步数范围
  minStep: 18000
  maxStep: 28000
