# Zepp-Life-Plugin 配置文件

# 随机步数设置
minStep: 18000
maxStep: 28000

# 是否启用中转代理 (默认关闭，若遇到 429 报错或接口限流时建议开启并配置下方的 apiProxy 链接)
useProxy: false

# 接口中转代理 (填入自建的 Hugging Face 代理或其它反代链接)
# 格式如: https://siran002-zepp-proxy.hf.space
apiProxy: ""
